# movie_roulette/roulette/forms.py

from django import forms
# --- Make sure you import UserList, UserReview, and Comment from models ---
from .models import UserList, UserReview, Comment # Added Comment

class UserListForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter list name (e.g., Sci-Fi Favorites)',
            'class': 'w-full px-3 py-2 border border-gray-700 bg-gray-900 rounded-md placeholder-gray-500 text-white focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm'
        })
    )

    class Meta:
        model = UserList
        fields = ['name']

# --- FORM FOR REVIEWS ---
class ReviewForm(forms.ModelForm):
    # Use a ChoiceField for ratings to create a <select> dropdown
    rating = forms.ChoiceField(
        choices=[(i, f"{i/2.0} Stars") for i in range(1, 11)], # 1-10
        required=True,
        widget=forms.Select(attrs={
            'class': 'w-full px-3 py-2 border border-gray-600 bg-gray-900 rounded-md text-white focus:outline-none focus:ring-1 focus:ring-indigo-500'
        })
    )
    review_text = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'rows': 4,
            'placeholder': 'Write your review (optional)...',
            'class': 'w-full px-3 py-2 border border-gray-600 bg-gray-900 rounded-md placeholder-gray-500 text-white focus:outline-none focus:ring-1 focus:ring-indigo-500'
        })
    )

    class Meta:
        model = UserReview
        fields = ['rating', 'review_text']

# --- NEW COMMENT FORM ---
class CommentForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea(attrs={
            'rows': 2, # Changed rows to 2 for a more compact look in the feed
            'placeholder': 'Add a comment...',
            'class': 'w-full px-3 py-2 border border-gray-600 bg-gray-900 rounded-md placeholder-gray-500 text-white focus:outline-none focus:ring-1 focus:ring-indigo-500 text-sm' # Added text-sm
        }),
        max_length=500,
        # Remove the default label generated by Django
        label=''
    )

    class Meta:
        model = Comment
        fields = ['text']