# Generated by Django 5.2.7 on 2025-10-12 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('list_type', models.CharField(choices=[('FAVORITE', 'Favorite'), ('HISTORY', 'History')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'movie_id', 'list_type')},
            },
        ),
    ]
