# Generated by Django 5.2.7 on 2025-10-12 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('list_type', models.CharField(choices=[('FAVORITE', 'Favorite'), ('HISTORY', 'History')], max_length=10)),
                ('content_type', models.CharField(choices=[('MOVIE', 'Movie'), ('TV', 'TV Show')], default='MOVIE', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'tmdb_id', 'list_type', 'content_type')},
            },
        ),
        migrations.DeleteModel(
            name='UserMovie',
        ),
    ]
