# Generated by Django 5.2.7 on 2025-10-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
