# Generated by Django 5.2.7 on 2025-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='list_type',
            field=models.CharField(choices=[('FAVORITE', 'Favorite'), ('HISTORY', 'History'), ('WATCHLIST', 'Watchlist')], max_length=10),
        ),
    ]
