# Generated by Django 5.2.7 on 2025-10-23 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_alter_usercontent_list_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='list_type',
            field=models.CharField(choices=[('FAVORITE', 'Favorite'), ('HISTORY', 'History'), ('WATCHLIST', 'Watchlist'), ('CUSTOM', 'Custom')], max_length=10),
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='usercontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='custom_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roulette.userlist'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontent',
            unique_together={('user', 'tmdb_id', 'content_type', 'list_type', 'custom_list')},
        ),
    ]
