# Generated by Django 5.2.7 on 2025-10-25 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('roulette', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_object_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlist',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Describe your list.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this list viewable by others?'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
