# Generated by Django 5.2.7 on 2025-10-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0012_sharedlistpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make this list viewable by others?'),
        ),
    ]
