# Generated by Django 5.2.7 on 2026-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0014_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userreview',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
