# Generated by Django 5.2.7 on 2026-05-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0016_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers only'), ('PRIVATE', 'Only me')], default='PUBLIC', max_length=10),
        ),
    ]
