# Generated by Django 5.2.7 on 2026-05-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0017_userreview_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='release_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
